### ISSUE TITLE
Search crash

### ISSUE THREAD

**Issue by Kiliggggg** [apache/lucenenet#1013]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

It's sporadic. We haven't found a pattern yet.
Error:
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.IO.UnmanagedMemoryAccessor.ReadByte(Int64)
   at Lucene.Net.Store.DataInput.ReadVInt32()
   at Lucene.Net.Codecs.Lucene41.Lucene41PostingsReader.ReadVInt32Block(Lucene.Net.Store.IndexInput, Int32[], Int32[], Int32, Boolean)
   at Lucene.Net.Codecs.Lucene41.Lucene41PostingsReader+BlockDocsEnum.RefillDocs()
   at Lucene.Net.Codecs.Lucene41.Lucene41PostingsReader+BlockDocsEnum.NextDoc()
   at Lucene.Net.Search.Weight+DefaultBulkScorer.ScoreAll(Lucene.Net.Search.ICollector, Lucene.Net.Search.Scorer)
   at Lucene.Net.Search.IndexSearcher.Search(System.Collections.Generic.IList`1<Lucene.Net.Index.AtomicReaderContext>, Lucene.Net.Search.Weight, Lucene.Net.Search.ICollector)
   at Lucene.Net.Search.IndexSearcher.Search(Lucene.Net.Search.Weight, Lucene.Net.Search.ScoreDoc, Int32)
   at EDiscovery.Core.Search.Searcher.Search(EDiscovery.Core.Query.Query, EDiscovery.Core.Query.Sort, EDiscovery.Core.Query.ScoreDoc, Int32)

### Lucene.NET Version

4.8.0-beta00016

### .NET Version

.NET 8

### Operating System

Linux

**Comment by NightOwl888** [comment]
Could you try upgrading to 4.8.0-beta00017 to see if it still happens?

**Comment by Kiliggggg** [comment]
> Could you try upgrading to 4.8.0-beta00017 to see if it still happens?

Got it, I will try it then update the result, thank you.

**Comment by Kiliggggg** [comment]
We are using the 4.8.0-beta00017 but the error still exists.

**Comment by florisrobbemont** [comment]
I'm also getting this error with 4.8.0-beta00017. Even when I clone the latest master it keeps crashing.

My setup is not that complex:
- Multiple threads using a single SearchManager
- Simple FacetsCollector + FacetCounter (FastTaxonomyFacetCounts)

```csharp
public static Dictionary<string, FacetResult> GetFacetResults(this BooleanQuery facetQuery, ILuceneIndex index, FacetsConfig facetsConfig)
    {
        var results = new Dictionary<string, FacetResult>();

        var searcher = index.SearcherManager.Acquire();
        try
        {
            // This collector accumulates all hits for faceting
            var fc = new FacetsCollector();
            FacetsCollector.Search(searcher, facetQuery, int.MaxValue, fc);
                        
            // Get the facet counts
            var facetCounts = new FastTaxonomyFacetCounts(index.FacetReader, facetsConfig, fc);

            // For each facetable field, gather its facet
            foreach (var facetField in facetsConfig.DimConfigs.Keys)
            {
                var fr = facetCounts.GetTopChildren(int.MaxValue, facetField);

                if (fr != null)
                {
                    // store it using the same "key" in results:
                    results[facetField] = fr;
                }
            }
        }
        finally
        {
            index.SearcherManager.Release(searcher);
            searcher = null;
        }

        return results;
    }
```

At first the exception was random, but when I run this method 10 times simultaneously the error starts popping up more often.

When I attach a debugger it always seems to crash on something in PriorityQueue<T>. But I can't figure out if this is a multi-threading issue (PriorityQueue<T> doesn't seem to be shared, because even when I synclock all the different methods the crash still happen).

So it doesn't feel like a concurrency bug, although it gets triggered more when doing concurrent searches.

Let me know if you need anything from me. We're about 3-4 weeks from going into production with this, so we're highly motivated to make this work ;)

**Comment by Kiliggggg** [comment]
Do we have any update

**Comment by paulirwin** [comment]
I don't have an update at this time, but I've added it to the beta 18 milestone to track the progress. This would be a great issue to get help from the community to look into the possible cause.

**Comment by paulirwin** [comment]
@NightOwl888 I wonder if this is related to #1090. UnmanagedMemoryAccessor (in the original issue stack trace) [is returned by MemoryMappedFile.CreateViewAccessor](https://learn.microsoft.com/en-us/dotnet/api/system.io.unmanagedmemoryaccessor?view=net-9.0#remarks), so that smells like it's related. 

@Kiliggggg @florisrobbemont Can either of you confirm if you're using MMapDirectory? If so, if you change it to another directory implementation (SimpleFSDirectory or NIOFSDirectory, or even RAMDirectory if the index can fit in memory), does it still happen?

**Comment by NightOwl888** [comment]
Given that the crash happens in PriorityQueue (could it be ValuePriorityQueue?), it seems possible that this is due to running on a machine with very little stack space, although I would expect there to be a StackOverflowException not an AccessViolationException. The default value that we provided in beta 17 is pretty high, 2048 bytes (or 1024 characters). This may not be optimal for all environments. 

This is just the maximum value that is allowed on the stack before falling back to using array pool on the heap, so it can be lowered to a more acceptable value if your system is running into problems without any ill effects (I wouldn't recommend going below 32, though).

The value can be changed, since it is a system property named `maxStackByteLimit`.

### Option 1 - Environment Variables

Configure the `maxStackByteLimit` variable, which must be prefixed with `lucene:`.

Name: `lucene:maxStackByteLimit`
Value: `256`

### Option 2 - Self-Contained Custom Configuration Provider

Here is a minimal self-contained implementation, that requires references on:

```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.3" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Abstractions" Version="9.0.3" />
  </ItemGroup>
```

```c#
    public sealed class SystemConfigurationFactory : IConfigurationFactory
    {
        private static readonly IConfiguration config = new SystemConfiguration();

        public IConfiguration GetConfiguration() => config;
    }

    public sealed class SystemConfiguration : IConfiguration
    {
        private readonly ConcurrentDictionary<string, string?> systemProperties = new ConcurrentDictionary<string, string?>
        {
            ["maxStackByteLimit"] = "256",
        };

        public string? this[string key]
        {
            get => systemProperties.TryGetValue(key, out var value) ? value : null;
            set => systemProperties[key] = value;
        }

        public IEnumerable<IConfigurationSection> GetChildren()
        {
            // Return only the first-level keys as sections
            var sectionKeys = systemProperties.Keys
                .Select(k => k.Split([':'], 2)[0])
                .Distinct();

            return sectionKeys.Select(k => new ConfigurationSection(this, k));
        }

        public IChangeToken GetReloadToken() => NullChangeToken.Singleton;

        public IConfigurationSection GetSection(string key)
        {
            return new ConfigurationSection(this, key);
        }

        private class ConfigurationSection : IConfigurationSection
        {
            private readonly SystemConfiguration parent;
            public string Key { get; }
            public string Path => Key;
            public string? Value
            {
                get => parent[Key];
                set => parent[Key] = value;
            }

            public ConfigurationSection(SystemConfiguration parent, string key)
            {
                this.parent = parent;
                Key = key;
            }

            public IEnumerable<IConfigurationSection> GetChildren()
            {
                var sectionPrefix = Key + ":";
                var childKeys = parent.systemProperties.Keys
                    .Where(k => k.StartsWith(sectionPrefix))
                    .Select(k => k.Substring(sectionPrefix.Length).Split(':')[0])
                    .Distinct();

                return childKeys.Select(k => new ConfigurationSection(parent, sectionPrefix + k));
            }

            public IChangeToken GetReloadToken() => NullChangeToken.Singleton;

            public IConfigurationSection GetSection(string key)
            {
                return new ConfigurationSection(parent, $"{Key}:{key}");
            }

            // Explicit implementation for IConfiguration members
            string? IConfiguration.this[string key]
            {
                get => parent[$"{Key}:{key}"];
                set => parent[$"{Key}:{key}"] = value;
            }

            IEnumerable<IConfigurationSection> IConfiguration.GetChildren() => GetChildren();

            IChangeToken IConfiguration.GetReloadToken() => GetReloadToken();

            IConfigurationSection IConfiguration.GetSection(string key) => GetSection(key);
        }
    }
```

And your application startup would look like:

```c#
ConfigurationSettings.SetConfigurationFactory(new SystemConfigurationFactory());
```

Note that I haven't tested this, so there may be some kinks to work out. Also, be aware that this will disable the built-in environment variable provider so none of the `lucene:` prefixed environment variables will work.

### Option 3 - Standard (or Custom) Configuration Providers

Alternatively, you could use existing `Microsoft.Extension.Configuration` providers by providing a pass-through implementation of `IConfiguarationFactory`, as follows.

```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="9.0.3" />
  </ItemGroup>
```


```c#
    public sealed class ConfigurationFactory : IConfigurationFactory
    {
        private readonly IConfiguration configuration;

        public ConfigurationFactory(IConfiguration configuration)
        {
            this.configuration = configuration ?? throw new ArgumentNullException(nameof(configuration));
        }

        public IConfiguration GetConfiguration()
        {
            return configuration;
        }
    }
```

This can be used like so:

```c#
var configuration = new ConfigurationBuilder() // Note there should only be 1 instance of ConfigurationBuilder for your entire app
    .AddEnvironmentVariables(prefix: "lucene:") // Use a custom prefix to only load Lucene.NET settings
    .AddJsonFile("appsettings.json", optional: true)
    .Build();
ConfigurationSettings.SetConfigurationFactory(new ConfigurationFactory(configuration));
```

Then you could put your application settings in the `appsettings.json` file, like so:

```c#
{
    "maxStackByteLimit": "256"
}
```

Do note that the above implementation won't detect any changes to the file at runtime, though.

You could alternatively use one or more of the other providers, for example the [Microsoft.Extensions.Configuration](https://www.nuget.org/packages/Microsoft.Extensions.Configuration/latest) contains an in-memory provider.

----------------------------

All of that said, changing the directory implementation could be a way to quickly rule out `MMapDirectory` as the cause, although the other implementations are not designed to scale to as many reads as `MMapDirectory`.

**Comment by paulirwin** [comment]
Initial investigation of this issue has resulted in possible reproductions of a couple scenarios in which this can occur. I've given this critical priority for the release given the multiple reports of users encountering this. I'll post more details when I get further into this.

**Comment by paulirwin** [comment]
An update on this: I have definitively found the cause of the originally reported crash. And it's fairly interesting, at least to me.

### Workaround

First, a workaround (which could suffice as a TL;DR). This is a MMapDirectory issue only (as indicated by the "UnmanagedMemoryAccessor" in the stack trace, which is an inlined call from memory-mapped file code). You can work around this issue in the meantime by switching to a different directory implementation, like SimpleFSDirectory or NIOFSDirectory.

### Detailed Explanation

To understand this, it's worth looking at upstream Lucene for historical context. MMapDirectory has this thing called the ["unmap hack"](https://github.com/apache/lucene/blob/f01152a5909fa6059f4f1d4aeb4e14968ef1d8c2/lucene/core/src/java/org/apache/lucene/store/MMapDirectory.java#L154-L170) to work around a missing feature in the JDK. This defaults to being enabled if [it is supported in your Java runtime](https://github.com/apache/lucene/blob/f01152a5909fa6059f4f1d4aeb4e14968ef1d8c2/lucene/core/src/java/org/apache/lucene/store/MMapDirectory.java#L137-L152), but can be manually turned on or off. 

The unmap hack will deterministically try to unmap the mapped file when the IndexInput is closed, except it has a gnarly flaw: if this is done by another thread and a different thread still has it mapped and tries to read, it will crash the JVM with a SIGSEGV (basically, an AccessViolationException - sound familiar?). (And FYI: this is called a "hack" because it pokes at internals via reflection to do this unmap, which is indeed a hack.)

If you _don't_ have the unmap hack turned on, then it will fall back to the JVM's [MappedByteBuffer](https://docs.oracle.com/javase/8/docs/api/java/nio/MappedByteBuffer.html) default behavior, which will "remain valid until the buffer itself is garbage-collected." That prevents the SIGSEGV, but that means that file handles are not deterministically cleaned up until GC time. This aligns with the [docs](https://github.com/apache/lucene/blob/f01152a5909fa6059f4f1d4aeb4e14968ef1d8c2/lucene/core/src/java/org/apache/lucene/store/MMapDirectory.java#L50-L54): "Only when GC finally collects the underlying objects, which could be quite some time later, will the file handle be closed."

(Aside: this comment also blames this on a Sun JVM "bug," which I assume they meant "bug" in the sense of "bug tracker" since it's more of a feature request for a missing API. The link in the docs has since bit-rotted, but is available now here: https://bugs.openjdk.org/browse/JDK-4724038 - the core request was to add an unmap method. I'm not sure this would have definitively solved it alone; it would have also required reworking the Lucene code. Regardless, this was closed in favor of the FFM API that was added in Java 22, which Lucene 10.x has since adopted.)

So Lucene as of 4.x requires you to choose from two not-great options with MMapDirectory: either non-deterministically clean up the file handles potentially "quite some time later" via GC, or risk a SIGSEGV with concurrent closes. We currently take the latter approach, accidentally. In other words, we have the "unmap hack" effectively applied in our code all of the time.

While we _could_ make our users have this same dilemma, I think we can reach a middle-ground, which I'm attempting to do now with the new PR #1361: deterministically clean up when called by the same thread, or non-deterministically clean up at GC time when called by a different thread. This demonstrably avoids an AVE in the concurrent case (and falls back to the MappedByteBuffer-like behavior), and in the same-thread case is able to safely, deterministically clean up at that moment.

Also note that we can't take clever approaches like per-clone independent mappings, thread-local storage, etc. to try to avoid this dilemma, because we could exhaust address space with multiple redundant mappings. Synchronizing around the state fixes the AVE and allows us to deterministically clean up, but at the expense of performance; and if MMapDirectory is as slow as SimpleFSDirectory, then what even is the point of its existence, other than possibly reducing some buffer memory churn?

I attempted analyzing what it would take to backport the Lucene 10.x approach, but the FFM API is quite big and complex, and doesn't have a direct .NET equivalent as far as I can tell from a first pass at research. It'll require more analysis later when we get to porting the 10.x code, or if this PR is unacceptable for some reason.

Regardless of how this solution and PR plays out, I think we should strongly consider removing it as a default directory implementation from `FSDirectory.Open` in all cases, and allow people to opt-in to using this if they determine that it works reliably for their use cases. It's perhaps a good thing that it was the default, because otherwise we wouldn't know about these bugs. But, given the tradeoffs, I think it's best to default to a stable and safe option instead of this potentially-non-deterministic behavior. (Related: this may influence #1301 and I'll certainly propose this over there.)
