### ISSUE TITLE
lucene-cli exception on starting

### ISSUE THREAD

**Issue by mjebrahimi** [apache/lucenenet#470]
I installed the cli using the following command.
```ini
> dotnet tool install --global lucene-cli --version 4.8.0-beta00014
``` 

I received the following exception while starting the cli using `lucene` command.

```ini
Unhandled exception. System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found and is not optional. The physical path is 'C:\Users\Ebrahimi\.dotnet\tools\.store\lucene-cli\4.8.0-beta00014\lucene-cli\4.8.0-beta00014\tools\netcoreapp3.1\any\appsettings.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Lucene.Net.Cli.Program.Main(String[] args) in D:\a\1\s\src\dotnet\tools\lucene-cli\Program.cs:line 27
```

I solved the problem by manually downloading the https://github.com/apache/lucenenet/blob/master/src/dotnet/tools/lucene-cli/appsettings.json file and putting it in the path `C:\Users\Ebrahimi\.dotnet\tools\.store\lucene-cli\4.8.0-beta00014\lucene-cli\4.8.0-beta00014\tools\netcoreapp3.1\any\`.

But basically this error should not have happened.

**Comment by laimis** [comment]
This was fixed here: https://github.com/apache/lucenenet/pull/455 and will be available with 4.8.0-beta00015 release. Your workaround is the way to get around this issue until the release with the fix goes out.
