### ISSUE TITLE
Intermittent Lucene.Net.Spatial Issue

### ISSUE THREAD

**Issue by deiniolcarter** [apache/lucenenet#562]
Hello,

We are currently experiencing intermittent issues when using Lucene for searches in combination with the Lucene.Net.Spatial library. The problem seems to be exacerbated by the use of load-balanced Azure app services, however it has been known to occur on a local development machine.

We are using Umbraco as our CMS with Examine used as an extension to Lucene.Net. However, all of the custom code that I have written interacts directly with the Lucene.Net library. We have extended the built-in Umbraco ExternalIndex and non-geo searches seem to cause no issues. We have also followed all of the recommended steps in the Umbraco Load Balancing Guide for Azure.

Any help/insight would be greatly appreciated!

NuGet Packages: Umbraco 8.15.0, Examine 1.2.1, Lucene.Net 3.0.3, Lucene.Contrib 3.0.3, Lucene.Contrib.Spatial 3.0.3, Spatial4n.Core 0.3.0, System.Spatial 5.8.5

```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.

Parameter name: index
           at System.Collections.BitArray.Get(Int32 index)
           at Lucene.Net.Spatial.Util.FixedBitSet.Get(Int32 index) in d:\Lucene.Net\FullRepo\trunk\src\contrib\Spatial\Util\FixedBitSet.cs:line 100
           at Lucene.Net.Spatial.Vector.DistanceValueSource.DistanceDocValues.DoubleVal(Int32 doc) in d:\Lucene.Net\FullRepo\trunk\src\contrib\Spatial\Vector\DistanceValueSource.cs:line 76
           at Lucene.Net.Spatial.Vector.DistanceValueSource.DistanceDocValues.FloatVal(Int32 doc) in d:\Lucene.Net\FullRepo\trunk\src\contrib\Spatial\Vector\DistanceValueSource.cs:line 70
           at Lucene.Net.Spatial.Util.ReciprocalFloatFunction.FloatDocValues.FloatVal(Int32 doc) in d:\Lucene.Net\FullRepo\trunk\src\contrib\Spatial\Util\ReciprocalFloatFunction.cs:line 59
           at Lucene.Net.Search.Function.DocValues.DoubleVal(Int32 doc) in d:\Lucene.Net\FullRepo\trunk\src\core\Search\Function\DocValues.cs:line 82
           at Lucene.Net.Spatial.Util.ValueSourceFilter.ValueSourceFilteredDocIdSet.Match(Int32 doc) in d:\Lucene.Net\FullRepo\trunk\src\contrib\Spatial\Util\ValueSourceFilter.cs:line 67
           at Lucene.Net.Search.FilteredDocIdSet.AnonymousClassFilteredDocIdSetIterator.Match(Int32 docid) in d:\Lucene.Net\FullRepo\trunk\src\core\Search\FilteredDocIdSet.cs:line 70
           at Lucene.Net.Search.FilteredDocIdSetIterator.Advance(Int32 target) in d:\Lucene.Net\FullRepo\trunk\src\core\Search\FilteredDocIdSetIterator.cs:line 77
           at Lucene.Net.Search.FilteredQuery.AnonymousClassWeight.AnonymousClassScorer.Advance(Int32 target) in d:\Lucene.Net\FullRepo\trunk\src\core\Search\FilteredQuery.cs:line 103
           at Lucene.Net.Search.ConjunctionScorer.Advance(Int32 target) in d:\Lucene.Net\FullRepo\trunk\src\core\Search\ConjunctionScorer.cs:line 113
           at Lucene.Net.Search.BooleanScorer2.Advance(Int32 target) in d:\Lucene.Net\FullRepo\trunk\src\core\Search\BooleanScorer2.cs:line 409
           at Lucene.Net.Search.BooleanScorer2.SingleMatchScorer.Advance(Int32 target) in d:\Lucene.Net\FullRepo\trunk\src\core\Search\BooleanScorer2.cs:line 265
           at Lucene.Net.Search.ReqOptSumScorer.Score() in d:\Lucene.Net\FullRepo\trunk\src\core\Search\ReqOptSumScorer.cs:line 78
           at Lucene.Net.Search.BooleanScorer2.Score() in d:\Lucene.Net\FullRepo\trunk\src\core\Search\BooleanScorer2.cs:line 403
           at Lucene.Net.Search.Function.CustomScoreQuery.CustomScorer.Score() in d:\Lucene.Net\FullRepo\trunk\src\core\Search\Function\CustomScoreQuery.cs:line 528
           at Lucene.Net.Search.TopScoreDocCollector.InOrderTopScoreDocCollector.Collect(Int32 doc) in d:\Lucene.Net\FullRepo\trunk\src\core\Search\TopScoreDocCollector.cs:line 49
           at Lucene.Net.Search.Scorer.Score(Collector collector) in d:\Lucene.Net\FullRepo\trunk\src\core\Search\Scorer.cs:line 68
           at Lucene.Net.Search.IndexSearcher.Search(Weight weight, Filter filter, Collector collector) in d:\Lucene.Net\FullRepo\trunk\src\core\Search\IndexSearcher.cs:line 228
           at Lucene.Net.Search.IndexSearcher.Search(Weight weight, Filter filter, Int32 nDocs) in d:\Lucene.Net\FullRepo\trunk\src\core\Search\IndexSearcher.cs:line 188
           at Lucene.Net.Search.Searcher.Search(Query query, Filter filter, Int32 n) in d:\Lucene.Net\FullRepo\trunk\src\core\Search\Searcher.cs:line 108
    at Lucene.Net.Search.Searcher.Search(Query query, Int32 n) in d:\Lucene.Net\FullRepo\trunk\src\core\Search\Searcher.cs:line 118
```

**Comment by NightOwl888** [comment]
Thanks for the report.

We are no longer supporting Lucene.NET 3.0.3 and the original team that ported it is no longer involved in the project. But this is primarily because all of our effort is going into 4.8.0 and we haven't looked into what it would take to resurrect 3.0.3 to begin patching it.

## Option 1 - Patch 3.0.3 Yourself

According to the [3.0.3 release blog post](https://blogs.apache.org/lucenenet/entry/lucene_net_3_0_3), the tag that corresponds to it is [Lucene.Net_3_0_3_RC2_final](https://github.com/apache/lucenenet/tree/Lucene.Net_3_0_3_RC2_final).  

Do note that there are several 3.x branches which may be patched beyond that tag, but I haven't looked into what these patches are fixing, nor have they been verified:

1. [3.0.3 (branch - has commits after the 2012-10-26 release date)](https://github.com/apache/lucenenet/tree/3.0.3)
2. [3.0.3-2 (branch - last commit 2012-09-27)](https://github.com/apache/lucenenet/tree/3.0.3-2)
3. [branch_3x (branch - has commits after the 2012-10-26 release date)](https://github.com/apache/lucenenet/tree/branch_3x)
4. [branch_3.0x (branch - last commit 2014-09-07)](https://github.com/apache/lucenenet/tree/branch_3.0x)

There are also several patches that RavenDB has done to 3.0.3 in their own fork:

- https://github.com/ravendb/lucenenet


If you are willing to do the footwork to figure out which of these options best corresponds to the 3.0.3 release and/or verify any patches to the branch that should go into another release, we could make sure it gets released and then we would have a way to continue patching it.

Do note that the `.sln` files are a bit hard to find. They are in the [build folder](https://github.com/apache/lucenenet/tree/Lucene.Net_3_0_3_RC2_final/build). No objections if you wish to change this to a single `.sln` file with the latest `.csproj` project file format, but we probably don't want to go down the road of trying to support .NET Standard/.NET Core/.NET 5/.NET 6 due to the amount of complexity involved.

Note also that it is an Apache requirement that the project must build and be testable via command line in order to [create a release](https://www.apache.org/legal/release-policy.html).

To make it clear that this is still a patched 3.0.3 build, it should be versioned 3.0.3._n_, where _n_ increments with each release.

## Option 2 - Upgrade to 4.8.0-beta00015

I don't know if all of those components support 4.8.0-beta00015, but if so, I would recommend upgrading because we can definitely patch 4.8.0 and will be able to continue supporting it in the future.
